---

- name: Create vikunja files directory
  file:
    path: "~/vikunja/files"
    state: directory

- name: Copy all files from local to remote host
  ansible.builtin.copy:
    src: "/tmp/vikunja/files"
    dest: "~/vikunja/files"