---

- name: Trash default nginx config
  shell: "mv {{ nginx_config_path }}/default /tmp/"
  ignore_errors: true

- name: Build nginx config
  vars: 
    BaseDomainName: "{{ lookup('community.general.passwordstore', 'homeserver.setup/secrets/1/do_base_domain', errors='ignore') }}"
    SubDomainName: "{{ lookup('community.general.passwordstore', 'homeserver.setup/secrets/1/do_name', errors='ignore') }}"
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_config_path }}/{{ SubDomainName }}.conf"
  notify:
    - restart php-fpm
    - restart nginx

- name: Configure nginx HTTPS through certbot
  expect:
    command: certbot
    responses:
      (.*)activate HTTPS for(.*): "\n"
      (.*)reinstall this existing certificate(.*): "1"
      (.*)Make all requests redirect to secure HTTPS(.*): "2"
  notify:
    - restart nginx
