---

- name: Copy from local to remote host
  ansible.builtin.copy:
    src: "/tmp/backup.sql"
    dest: "/tmp/backup.sql"

- name: Restore database from backup
  community.mysql.mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: "{{ FireflyUsernameDefault }}"
    login_password: "{{ FireflyPasswordDefault }}"
    name: firefly
    state: import
    target: "/tmp/backup.sql"
