---

- name: Set up rclone and start regular backup cron job
  vars:
    Name: "{{ lookup('community.general.passwordstore', 'backblaze' + '/name', errors='ignore') }}"
    Account: "{{ lookup('community.general.passwordstore', 'backblaze' + '/account', errors='ignore') }}"
    Key: "{{ lookup('community.general.passwordstore', 'backblaze' + '/key', errors='ignore') }}"
    Bucket: "{{ lookup('community.general.passwordstore', 'backblaze' + '/bucket', errors='ignore') }}"
  block:
    - name: Create rclone config directory
      file:
        path: "~/.config/rclone"
        state: directory

    - name: Build rclone config
      template:
        src: rclone.conf.j2
        dest: "~/.config/rclone/rclone.conf"

    - name: Install rclone package
      apt:
        pkg:
        - rclone
        state: present

    - name: Start database backup cron job
      ansible.builtin.cron:
        name: "backup_all_databases_to_b2"
        minute: "30"
        hour: "3,13"
        job: "mysqldump -u root --all-databases > backup.sql && rclone copy backup.sql {{ Name }}:{{ Bucket }}/backup/homeserver/mysql"

    - name: Start vikunja files backup cron job
      ansible.builtin.cron:
        name: "backup_vikunja_files_to_b2"
        minute: "45"
        hour: "3,13"
        job: "rclone copy ~/vikunja/files {{ Name }}:{{ Bucket }}/backup/homeserver/vikunja/files"
