---

- name: Create temporary vikunja files directory
  file:
    path: "/tmp/vikunja"
    state: directory

- name: Fetch files backup from backblaze archive to local
  shell: "rclone copy $(pass backblaze/name):$(pass backblaze/bucket)/backup/homeserver/vikunja /tmp/vikunja"
  args:
    executable: /bin/bash
