---

- name: Fetch backup from backblaze archive to local
  shell: "rclone copy $(pass backblaze/name):$(pass backblaze/bucket)/backup/bzweek/mysql/backup.sql /tmp/"
  args:
    executable: /bin/bash
