---

- name: Set up DigitalOcean infrastructure
  hosts: local
  roles:
    - role: setup-infra
      tags:
        - infra
        - digitalocean

- name: Set up pre-prequisites
  hosts: local
  roles:
    - role: prepare-local
      tags:
        - restore
        - personal
        - asslpl

- name: Set up services on bzweek
  hosts: bzweek-root
  vars_files:
          - config.yml
  roles:
    - role: setup-firefly
      tags:
        - personal
        - finance

    - role: setup-ainv
      tags:
        - asslpl

    - role: coopdevs.certbot_nginx
      vars:
        domain_name: bzweek.taptappers.club
        letsencrypt_email: rounakdatta12@gmail.com
        certbot_force_update: false
      tags:
        - security

    - role: setup-phpmyadmin
      tags:
        - asslpl

    - role: setup-nginx
      tags:
        - stitch
